# Generated by Django 6.0.7 on 2026-07-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='comissao_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se vazio, usa o percentual padrão da oficina', max_digits=5, null=True),
        ),
    ]
