# Generated by Django 6.0.7 on 2026-07-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_semana5_6_diferenciacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='papel',
            field=models.CharField(choices=[('dono', 'Administrador'), ('recepcao', 'Recepção'), ('mecanico', 'Mecânico'), ('financeiro', 'Financeiro')], default='recepcao', max_length=20),
        ),
    ]
