# Generated by Django 6.0.7 on 2026-07-28 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('orcamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('aguardando_peca', 'Aguardando peça'), ('aguardando_aprovacao', 'Aguardando aprovação'), ('pronta', 'Pronta'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada')], default='aberta', max_length=30)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10)),
                ('pagamento_status', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago')], default='pendente', max_length=10)),
                ('previsao_entrega', models.DateTimeField(blank=True, null=True)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('token_publico', models.CharField(blank=True, db_index=True, max_length=64)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='core.cliente')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens', to='core.oficina')),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens', to='orcamentos.orcamento')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_responsavel', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens', to='core.veiculo')),
            ],
            options={
                'verbose_name': 'Ordem de serviço',
                'verbose_name_plural': 'Ordens de serviço',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OrdemItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('servico', 'Serviço'), ('peca', 'Peça')], max_length=10)),
                ('descricao', models.CharField(max_length=200)),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('peca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.peca')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servico')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ordens.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('imagem', models.ImageField(upload_to='ordens/%Y/%m/')),
                ('legenda', models.CharField(blank=True, max_length=120)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ordens.ordemservico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], default='entrada', max_length=10)),
                ('item', models.CharField(max_length=120)),
                ('ok', models.BooleanField(default=False)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='ordens.ordemservico')),
            ],
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['oficina', 'status'], name='ordens_orde_oficina_04db9e_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['oficina', 'prioridade'], name='ordens_orde_oficina_13b738_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ordemservico',
            unique_together={('oficina', 'numero')},
        ),
    ]
