# Generated by Django 6.0.7 on 2026-07-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='estoque_baixado',
            field=models.BooleanField(default=False, help_text='Indica se as peças desta OS já foram debitadas do estoque.'),
        ),
    ]
