# Generated by Django 6.0.7 on 2026-07-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0003_backfill_token_publico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemfoto',
            options={'ordering': ['criado_em'], 'verbose_name': 'Foto da OS', 'verbose_name_plural': 'Fotos da OS'},
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='video_titulo',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='video_url',
            field=models.URLField(
                blank=True,
                default='',
                help_text='Link do vídeo (YouTube, Vimeo ou outro stream).',
            ),
        ),
    ]
