# Generated by Django 6.0.7 on 2026-07-28 21:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_compra_compraitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='comissao_padrao_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Percentual padrão de comissão sobre OS entregues', max_digits=5),
        ),
        migrations.AddField(
            model_name='oficina',
            name='pix_chave',
            field=models.CharField(blank=True, help_text='Chave Pix (CPF, CNPJ, e-mail, telefone ou aleatória)', max_length=120),
        ),
        migrations.AddField(
            model_name='oficina',
            name='pix_nome',
            field=models.CharField(blank=True, help_text='Nome do recebedor no Pix (máx. 25 caracteres)', max_length=25),
        ),
    ]
