# Generated by Django 6.0.7 on 2026-07-28 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversaAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('canal', models.CharField(choices=[('painel', 'Painel'), ('whatsapp', 'WhatsApp'), ('portal', 'Portal do cliente')], default='painel', max_length=20)),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('telefone_externo', models.CharField(blank=True, max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas_agente', to='core.cliente')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='core.oficina')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas_agente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversa do agente',
                'verbose_name_plural': 'Conversas do agente',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='MensagemAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('papel', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente'), ('system', 'Sistema'), ('tool', 'Ferramenta')], max_length=20)),
                ('conteudo', models.TextField()),
                ('tool_name', models.CharField(blank=True, max_length=80)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='agentes.conversaagente')),
            ],
            options={
                'verbose_name': 'Mensagem do agente',
                'verbose_name_plural': 'Mensagens do agente',
                'ordering': ['criado_em'],
            },
        ),
    ]
