# Generated by Django 6.0.7 on 2026-07-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemagente',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='agentes/audio/%Y/%m/'),
        ),
    ]
