# Generated by Django 6.0.7 on 2026-08-14 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0002_mensagem_audio'),
        ('core', '0004_oficina_configuracoes'),
        ('orcamentos', '0003_orcamento_token_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversaagente',
            name='contexto_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='conversaagente',
            name='etapa',
            field=models.CharField(choices=[('inicial', 'Inicial'), ('identificando_cliente', 'Identificando cliente'), ('identificando_veiculo', 'Identificando veículo'), ('montando_orcamento', 'Montando orçamento'), ('aguardando_confirmacao', 'Aguardando confirmação'), ('processando', 'Processando'), ('concluida', 'Concluída'), ('erro', 'Erro')], default='inicial', max_length=32),
        ),
        migrations.AddField(
            model_name='conversaagente',
            name='expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversaagente',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas_agente', to='orcamentos.orcamento'),
        ),
        migrations.AddField(
            model_name='conversaagente',
            name='ultima_mensagem_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversaagente',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas_agente', to='core.veiculo'),
        ),
    ]
