# Generated by Django 6.0.7 on 2026-08-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agentes", "0003_conversaagente_contexto_json_conversaagente_etapa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensagemagente",
            name="erro_processamento",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mensagemagente",
            name="status",
            field=models.CharField(
                choices=[
                    ("recebida", "Recebida"),
                    ("processando", "Processando"),
                    ("processada", "Processada"),
                    ("erro", "Erro"),
                ],
                default="processada",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mensagemagente",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("texto", "Texto"),
                    ("audio", "Áudio"),
                    ("imagem", "Imagem"),
                    ("arquivo", "Arquivo"),
                ],
                default="texto",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mensagemagente",
            name="whatsapp_message_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
