# Generated by Django 6.0.7 on 2026-08-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agentes", "0004_mensagemagente_erro_processamento_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mensagemagente",
            index=models.Index(
                fields=["conversa", "criado_em"], name="agentes_men_convers_f57201_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mensagemagente",
            index=models.Index(
                fields=["conversa", "status"], name="agentes_men_convers_f94eab_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mensagemagente",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("erro_processamento__gt", ""), ("status", "erro")),
                    models.Q(("status", "erro"), _negated=True),
                    _connector="OR",
                ),
                name="mensagem_erro_exige_detalhe",
            ),
        ),
    ]
