# Generated by Django 6.0.7 on 2026-07-28 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ordens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forma', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao', 'Cartão'), ('boleto', 'Boleto'), ('transferencia', 'Transferência'), ('outro', 'Outro')], default='pix', max_length=20)),
                ('data', models.DateField()),
                ('pago', models.BooleanField(default=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='core.oficina')),
                ('ordem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='ordens.ordemservico')),
            ],
            options={
                'verbose_name': 'Lançamento',
                'verbose_name_plural': 'Lançamentos',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
