# Generated by Django 6.0.7 on 2026-07-28 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='video_titulo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link do vídeo (YouTube, Vimeo ou outro stream).'),
        ),
        migrations.CreateModel(
            name='OrcamentoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('imagem', models.ImageField(upload_to='orcamentos/%Y/%m/')),
                ('legenda', models.CharField(blank=True, max_length=120)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='orcamentos.orcamento')),
            ],
            options={
                'verbose_name': 'Foto do orçamento',
                'verbose_name_plural': 'Fotos do orçamento',
                'ordering': ['criado_em'],
            },
        ),
    ]
