# Generated by Django 6.0.7 on 2026-07-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_orcamento_video_titulo_orcamento_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='token_publico',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
